version: '3.8'

services:
  speech-assistant:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - PORT=5050
    volumes:
      - ./moving_requests:/app/moving_requests
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 