version: '3.8'

services:
  speech-assistant:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - PORT=5050
    volumes:
      - ./call_log:/app/call_log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 